### ISSUE TITLE
Support ${config_loc} variable for suppressions.xml

### ISSUE THREAD

**Issue by Siedlerchr** [nikitasavinov/checkstyle-action#16]
Hi,

thanks for the extension, I really like the idea. I tried to integrate it in our project but it does not work, because it cannot resolve the variable:
We use it also in our gradle process 
https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_built_in_variables

https://github.com/JabRef/jabref/pull/6996

**Comment by nikitasavinov** [comment]
Resolved now, thanks to @tochi-y : https://github.com/nikitasavinov/checkstyle-action/pull/19
